### ISSUE TITLE
Guess_00

### ISSUE THREAD

**Issue by rentalhost** [WA-YI/Zelda-TOTK-LocFile#1]
Do you have some glue what guess_00, observation_00 and similar means to be?

**Comment by WA-YI** [comment]
These IDs are named by developer, which can only be explained by the NPC's logic file. But I don't have any ideas for files, but well upload another site if it can help.

**Comment by rentalhost** [comment]
I found that it has something to do with the "emotion" of the characters during speech. For example, when there is information "Guess_00" for Zelda, she makes a "doubt sound" when starting the speech. It's very subtle, and some characters are practically unnoticeable.
